name: Interview codebase.$(BuildId)
trigger:
 branches:
   include:
     - main
pool:
 vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: build
        pool: 
         vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: 'TodoAPI/TodoAPI.csproj'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: 'TodoAPI.Test/TodoAPI.Test.csproj'
              arguments: '--logger trx'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'custom'
              custom: 'tool'
              arguments: 'install --global dotnet-ef'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'custom'
              custom: 'ef'
              arguments: 'database update --project=TodoAPI'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: 'TodoAPI/TodoAPI.csproj'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            

  - stage: Deploy
    jobs:
      - job: deploy
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure subscription 1(62d23974-1452-401f-ae2f-b88e5377196d)'
              appType: 'webAppLinux'
              WebAppName: 'codebasecicd'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'